# Site settings
title: my Blog
name: Lynn # your name
email: 470549092@@qq.com # your email address
description: >
    Lynn's Blog. 
baseurl: "/Nice_Blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: LeeLeeLeeLeeLynn # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
